### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by segiddins** [DeskConnect/WFNotificationCenter#2]

**Comment by conradev** [comment]
@segiddins, I would love to have you review the documentation I wrote up.

Besides small typos and such, are there any high level questions that go unanswered for people looking at this library for the first time?

**Comment by segiddins** [comment]
Is there a PR I can look at?

**Comment by conradev** [comment]
Sorry, forgot to push it, it's in f05c615c08d9d0fd3b33ca36639785b0cc2922f1

**Comment by segiddins** [comment]
No, you did a pretty bang-up job! Now to just do #3 so everyone can read your beautiful docs on cocoadocs.org ;)

**Comment by conradev** [comment]
http://cocoadocs.org/docsets/WFNotificationCenter/0.1/Classes/WFDistributedNotificationCenter.html :)
