### ISSUE TITLE
CFMessagePortCreateRemote  is unavailable on iOS >= 7

### ISSUE THREAD

**Issue by JonasGessner** [DeskConnect/WFNotificationCenter#4]
I was replacing some deprecated property list methods and fixing a memory leak in the ports code and came across the CFMessagePort docs: https://developer.apple.com/library/prerelease/ios/documentation/CoreFoundation/Reference/CFMessagePortRef/index.html#//apple_ref/c/func/CFMessagePortCreateRemote 

`CFMessagePortCreateRemote:`

```
This method is not available on iOS 7 and later—it will return NULL and log a sandbox violation in syslog. See Concurrency Programming Guide for possible replacement technologies.
```

**Comment by AriX** [comment]
This documentation is outdated. CFMessagePorts can be created and used between apps in the same App Group if the CFMessagePort's name begins with the App Group identifier.
